document.head.innerHTML += '<link rel="stylesheet" href="/old.css">';
document.head.innerHTML += '<link rel="stylesheet" href="/style.css">';
document.head.innerHTML += '<link rel="stylesheet" href="/fonts.css">';
document.head.innerHTML += '<link rel="stylesheet" href="/music-reproductor.css">';
document.head.innerHTML += '<script src="/shNavigation.js"></script>';
document.head.innerHTML += '<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">';
document.head.innerHTML += '<link href="https://fonts.googleapis.com/css2?family=Cantarell&display=swap" rel="stylesheet"> ';
document.head.innerHTML += '<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;900&display=swap" rel="stylesheet"> ';
document.head.innerHTML += '<link href="https://fonts.googleapis.com/css?family=Source+Serif+Pro" rel="stylesheet">';
document.head.innerHTML += '<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">';